# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    gaps_in = 2
    gaps_out = 5, 10
    border_size = 1
    col.active_border = rgb(08b5ff) rgb(0800ff) rgb(08b5ff) rgb(0800ff) 45deg
    col.inactive_border = rgb(141414)

    # Change to niri-like side-scrolling layout
    layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.25

    active_opacity = 1.0
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
    enabled = yes
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = borderangle, 1, 300, linear, loop
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
